---
- hosts: k8smaster
  vars_files:
  - env_variables
  tasks:
    - name: backup the etcd component
      shell: ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save /opt/etcd_backup_$(date +"%Y_%m_%d_%I_%M_%p").db
      register: backup

    - debug:
        msg: "{{ backup }}"