---
- hosts: all
  vars_files:
  - env_variables
  tasks:
  - name: configure docker-ce repository
    shell: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no

  - name: install docker packages
    shell: sudo yum install docker-ce --nobest -y --allowerasing

  - name: restart the docker service and enable
    shell: sudo systemctl enable --now docker

  - name: set a pause after restart of service
    pause:
      seconds: 10

  - name: Add your user to the docker group
    shell: sudo usermod -aG docker $USER

  - name: verifyt the docker version
    shell: docker --version

  - name: pull and run a demo hello-world image
    shell: docker run hello-world

  - name: validate running image
    shell: docker ps -a
    register: image

  - name: display installed image
    debug:
      msg: "{{ image.stdout_lines }}"

  - name: set a pause at end of play
    pause:
      seconds: 10
