---
- hosts: k8smaster
  vars_files:
  - env_variables
  tasks:
  - name: install etcd binary on master node
    shell: |
      export RELEASE="3.3.13"
      wget https://github.com/etcd-io/etcd/releases/download/v${RELEASE}/etcd-v${RELEASE}-linux-amd64.tar.gz
      tar xvf etcd-v${RELEASE}-linux-amd64.tar.gz
      mv etcd-v${RELEASE}-linux-amd64/etcd /usr/local/bin
      mv etcd-v${RELEASE}-linux-amd64/etcdctl /usr/local/bin
      etcd --version
   
  - name: set a pause at end of playbook
    pause:
      seconds: 10
