---
- hosts: k8smaster
  vars_files:
  - env_variables
  tasks:
  - name: validate whether the cluster is ready
    shell: kubectl get nodes
    register: output

  - name: display installed cluster nodes output
    debug:
      msg: "{{  output.stdout_lines }}"
